"use client"

import { FormEvent, useEffect, useState } from "react"
import { AppShell } from "@/components/app-shell"
import { ProtectedRoute } from "@/components/protected-route"
import { useAuth } from "@/components/auth-provider"
import { createClient } from "@/lib/supabase/client"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"
import { Alert, AlertDescription } from "@/components/ui/alert"

export default function ProfilePage() {
  const { user } = useAuth(); const supabase = createClient(); const [form, setForm] = useState({ name: "", email: "", college: "", branch: "", semester: "", graduation_year: "", target_career: "" }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("")
  useEffect(() => { if (!user) return; supabase.from("profiles").select("name,email,college,branch,semester,graduation_year,target_career").eq("id", user.id).maybeSingle().then(({ data }: { data: { name?: string; email?: string; college?: string | null; branch?: string | null; semester?: string | null; graduation_year?: number | null; target_career?: string | null } | null }) => { setForm({ name: data?.name ?? user.user_metadata?.name ?? "", email: data?.email ?? user.email ?? "", college: data?.college ?? "", branch: data?.branch ?? "", semester: data?.semester ?? "", graduation_year: data?.graduation_year?.toString() ?? "", target_career: data?.target_career ?? "" }); setLoading(false) }) }, [supabase, user])
  function update(key: keyof typeof form, value: string) { setForm((current) => ({ ...current, [key]: value })) }
  async function save(event: FormEvent) { event.preventDefault(); if (!user) return; setSaving(true); setError(""); setMessage(""); const { error } = await supabase.from("profiles").upsert({ id: user.id, name: form.name.trim(), email: form.email, college: form.college.trim() || null, branch: form.branch.trim() || null, semester: form.semester.trim() || null, graduation_year: form.graduation_year ? Number(form.graduation_year) : null, target_career: form.target_career.trim() || null, updated_at: new Date().toISOString() }); setSaving(false); if (error) setError("We could not save your profile. Please try again."); else setMessage("Profile saved successfully.") }
  return <ProtectedRoute><AppShell title="Student Profile" description="Keep your academic background and career direction ready for future intelligence features."><main className="mx-auto max-w-3xl px-4 py-10 sm:px-6"><Card><CardHeader><CardTitle>Your profile</CardTitle><CardDescription>Your email is linked to your account and cannot be edited here.</CardDescription></CardHeader><CardContent>{loading ? <p className="text-muted-foreground">Loading profile...</p> : <form onSubmit={save} className="flex flex-col gap-6">{message && <Alert><AlertDescription>{message}</AlertDescription></Alert>}{error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}<div className="grid gap-5 sm:grid-cols-2"><div className="flex flex-col gap-2 sm:col-span-2"><Label htmlFor="name">Full Name</Label><Input id="name" required value={form.name} onChange={(e) => update("name", e.target.value)} /></div><div className="flex flex-col gap-2 sm:col-span-2"><Label htmlFor="email">Email</Label><Input id="email" type="email" readOnly value={form.email} /></div><div className="flex flex-col gap-2"><Label htmlFor="college">College</Label><Input id="college" value={form.college} onChange={(e) => update("college", e.target.value)} /></div><div className="flex flex-col gap-2"><Label htmlFor="branch">Branch</Label><Input id="branch" value={form.branch} onChange={(e) => update("branch", e.target.value)} /></div><div className="flex flex-col gap-2"><Label htmlFor="semester">Semester</Label><Input id="semester" value={form.semester} onChange={(e) => update("semester", e.target.value)} /></div><div className="flex flex-col gap-2"><Label htmlFor="graduation_year">Graduation Year</Label><Input id="graduation_year" type="number" min="2000" max="2100" value={form.graduation_year} onChange={(e) => update("graduation_year", e.target.value)} /></div><div className="flex flex-col gap-2 sm:col-span-2"><Label htmlFor="target_career">Target Career</Label><Input id="target_career" placeholder="e.g. Full Stack Developer" value={form.target_career} onChange={(e) => update("target_career", e.target.value)} /></div></div><Button type="submit" disabled={saving}>{saving ? "Saving..." : "Save profile"}</Button></form>}</CardContent></Card></main></AppShell></ProtectedRoute>
}
